# Generated by Django 2.2 on 2020-02-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friends',
        ),
    ]
