# Generated by Django 2.2 on 2020-02-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0003_order_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(default=2, on_delete=True, to='billing.BillingProfile'),
            preserve_default=False,
        ),
    ]
