# Generated by Django 2.2 on 2020-02-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='lastDate',
            field=models.DateField(),
        ),
    ]
