# Generated by Django 2.2 on 2020-02-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='billingProfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='billing.BillingProfile'),
        ),
    ]
